### PR TITLE
add cbor4ii to benchmarks

### PR DESCRIPTION
**Pull request by quininer**
:)

### CODE REVIEW

**Comment by djkoloski** [comment]
Looks like you just need to rerun `cargo fmt`. Make sure to pull first, I added one commit to pin the `cbor4ii` version to 0.3.1.

**Comment by quininer** [comment]
Since the old version of simd-json was revoked, I have to update it.

You may want to keep `Cargo.lock` to avoid this.

**Comment by djkoloski** [comment]
Thanks for the PR! Sorry about broken CI, I did a quick pass to fix that up.

**Comment by djkoloski** [comment]
The regex for parsing log outputs wasn't matching crates with numbers in their names. I've fixed that and stats for `cbor4ii` now appear in the README.

**Comment by quininer** [comment]
The results look worse than I expected, cbor4ii performs better than serde_cbor on all my test devices (amd, intel, aarch64), but not on github actions.

**Comment by djkoloski** [comment]
Are you testing with these benchmarks or another set of benchmarks?

**Comment by quininer** [comment]
Using this benchmark, my local first bench can get a score of 700us before submit, but only 1.3ms after merge.


^ before submit

Screenshot_20231102_121252
^ after merge

**Pull request merged**
