### PR TITLE
Major changes

### PR DESCRIPTION
**Pull request by arnabanimesh**
1. Update dependencies and make changes accordingly
2. Set PROTOC path in Windows at build time if not set already
3. Update flatc and protoc executables to the latest versions
4. Prevent flatbuffers related unused imports warnings from showing up

### CODE REVIEW

**Comment by arnabanimesh** [comment]
Also removed alkahest nightly feature comment from Cargo.toml, as it is still required in the latest rust compilers.

**Comment by arnabanimesh** [comment]
Formatted the modified files using `cargo fmt` too

**Comment by djkoloski** [comment]
It looks like there's a lot of noise in `Cargo.toml` from whitespace changes, could you fix those? Spaces inside curly braces is standard practice for manifests: https://github.com/rust-lang/cargo/blob/master/Cargo.toml

Did you format the auto-generated `*.rs` files from `protoc` and `flatc`? Those shouldn't be formatted but we can't opt out in a `rustfmt.toml` yet because the features [aren't](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#format_generated_files) [stable](https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#ignore).

The version bumps look good and I appreciate the fix for PROTOC on windows. Eventually we need a better system for updating the windows executables, but for now it works fine. I'll make sure the binaries are unchanged from the versions published on GitHub.

**Comment by arnabanimesh** [comment]
Made the necessary modifications to `Cargo.toml`

I did not run cargo fmt in my project. I just have `Format on save` turned on in `vscode`.
I did not format the auto generated files, these are created automatically due to the new version of the flatbuffers crate. Not to mention, it is simply not possible because rust-analyzer continues to overwrite those autogenerated files every time I tried to change.

**Comment by arnabanimesh** [comment]
I have updated the workflow file. Now it should work.

**Comment by djkoloski** [comment]
Thanks for the PR!

**Comment by arnabanimesh** [comment]
Line 27 of `bench_rkyv.rs` can be removed. I don't know why Rust compiler was showing error at back then.

**Pull request merged**
